language: node_js

node_js:
  - "8"
    
env:
  - DOCKER_COMPOSE_VERSION=1.14.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - ls -lah
  - docker-compose -f docker/test/docker-compose.yml up -d
  - docker-compose -f docker/test/docker-compose.yml ps
  - docker-compose -f docker/test/docker-compose.yml exec web npm install -g yarn
  - docker-compose -f docker/test/docker-compose.yml exec web yarn --production=false
  - docker-compose -f docker/test/docker-compose.yml exec web npm run _test
  - pwd
  - ls -lah

notifications:
  email:
    - $NOTIFICATIONS_EMAIL
  slack:
    secure: $NOTIFICATIONS_SLACK_SECURE

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master