version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ".:/src"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5858:5858"
    links:
      - "db"
    depends_on:
      - db
    environment:
      NODE_ENV: dev

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_DB: "${PGDB}"

  adminer:
    image: adminer
    ports:
      - 8080:8080