version: '3'
services:
  https-portal:
    image: steveltn/https-portal
    ports:
      - '80:80'
      - '443:443'
    links:
      - web
    restart: always
    environment:
      DOMAINS: "${HTTPSDOMAINS}"
      STAGE: 'production'
      # FORCE_RENEW: 'true'
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    links:
      - "db"
    depends_on:
      - db
    environment:
      NODE_ENV: prod
      PGPASSWORD: "${PGPASSWORD}"
      PGUSER: "${PGUSER}"
      PGDB: "${PGDB}"
    ports:
      - '3001:3001'
    volumes:
      - /src/node_modules

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_DB: "${PGDB}"
    depends_on:
      - auth

  auth:
      image: lipp/login-with
      environment:
        LW_JWT_SECRET: "${LW_JWT_SECRET}"
        LW_SESSION_SECRET: "${LW_SESSION_SECRET}"
        LW_SUBDOMAIN: "${LW_SUBDOMAIN}"
        LW_FACEBOOK_APPID: "${LW_FACEBOOK_APPID}"
        LW_FACEBOOK_APPSECRET: "${LW_FACEBOOK_APPSECRET}"