version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - web
    restart: always
    environment:
      DOMAINS: "${HTTPSDOMAINS}"
      STAGE: 'production'
      # FORCE_RENEW: 'true'
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    links:
      - "db"
    depends_on:
      - db
    environment:
      NODE_ENV: prod

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_DB: "${PGDB}"
