version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ".:/src"
    ports:
      - "3000:3000"
      - "3001:3001"
    links:
      - "db"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_DB: "${PGDB}"
