version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - web
    restart: always
    environment:
      DOMAINS: "${HTTPSDOMAINS}"
      STAGE: 'production'
      # FORCE_RENEW: 'true'

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    ports:
      - "80:3001"


